name: flutter_getx_git_repositories
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  #getx StateManagement
  get: 4.6.5
  flutter: 
    sdk: flutter
  #getx storage chache management
  get_storage: ^2.0.3
  #date and other formatter
  intl: ^0.17.0
  #splash page image
  lottie: ^2.2.0
  #drawer icons
  ternav_icons: ^1.0.0
  #responsive usage
  flutter_screenutil: ^5.6.0
  #network image chache management
  cached_network_image: ^3.2.3
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/models/json/
    - assets/images/
  uses-material-design: true

#  github_lottie.json

